name: .NET CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Change directory to src
      run: cd src

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  # Adjust to your desired .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Debug --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Set status check
      if: always()
      run: echo "::set-output name=status::success"
      id: status

  check_status:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check status
      run: |
        if [[ "${{ needs.build.outputs.status }}" == "success" ]]; then
          echo "Build successful!"
          exit 0
        else
          echo "Build failed!"
          exit 1
        fi
