name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x'

    - name: Restore dependencies
      run: dotnet restore ./src/Flow.Launcher.Plugin.Notion.csproj

    - name: Build
      run: dotnet build --configuration Release ./src/Flow.Launcher.Plugin.Notion.csproj
