name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Restore dependencies
      run: dotnet restore ./src/Flow.Launcher.Plugin.Notion.csproj

    - name: Build
      run: dotnet publish -c Release -r win-x64 --no-self-contained ./src/Flow.Launcher.Plugin.Notion.csproj

      # Attach the zip file to the pull request
    - name: Upload DLL zip artifact
      uses: actions/upload-artifact@v3
      with:
        name: Flow.Launcher.Plugin.Notion.dll
        path: "./src/bin/Release/win-x64/publish/Flow.Launcher.Plugin.Notion.dll"
